#!/usr/bin/env sh
set -e

error() {
  echo $@ >&2

  exit 1
}

if  [ "$1" = "version" ]; then
  exec cat /etc/VERSION
fi

[ -f ".env" ] && source .env

CMD="${0%/*}/gelli-${1:-help}"

shift || true

# Add this to your GELLI container startup
git config --global --add safe.directory "$PWD"

[ -f "$CMD" ] && exec "$CMD" "$@" || error UNKNOWN COMMAND: $1 >&2
