#!/usr/bin/env sh
set -e

error() {
  echo $@ >&2

  exit 1
}

if  [ "$1" = "version" ]; then
  exec cat /etc/VERSION
fi

[ -f ".env" ] && source .env

DIR="${0%/*}"
CMD="${DIR}/gelli-${1:-help}"

export PATH="$DIR:$PATH"

shift || true

[ -f "$CMD" ] && exec "$CMD" "$@" || error UNKNOWN COMMAND: $1 >&2
