#!/usr/bin/env sh
set -e

error() {
  echo $@ >&2

  exit 1
}

if  [ "$1" = "version" ]; then
  exec cat /etc/VERSION
fi

[ -f ".env" ] && source .env

DIR="${0%/*}"
CMD="${DIR}/gelli-${1:-help}"

export PATH="$DIR:$PATH"

shift || true

if [ -d ".gelli" ]; then
  [ -d  ".gelli/bin" ] && ln -sf "$PWD/.gelli/bin/*" /usr/local/bin/
  [ -d  ".gelli/tools" ] && ln -sf "$PWD/.gelli/tools/*" /usr/tools/
  [ -d  ".gelli/agents" ] && ln -sf "$PWD/.gelli/agents/*" /usr/agents/
fi

[ -f "$CMD" ] && exec "$CMD" "$@" || error UNKNOWN COMMAND: $1 >&2
