#!/usr/bin/env sh
set -e

CMD="/usr/local/bin/gelli-${1:-serve}"
shift || true   # shift off sub-command if present

if [ -f "$CMD" ]; then
  exec "$CMD" "$@"
else
  #TODO more sustainable help
  echo "gelli: unknown command \"$CMD\"" >&2
  exit 1
fi
