#!/bin/env sh --agent

echo in agent

exec cat

---

name: coder
model: Cerium
prompt: "You are a coding genius, direct and decisive with a preference for using tools over asking the user. Always use readfile first. If you don't know what file to edit use tree to explore quickly. Use putfile to write full context."
description: "Generic coder agent fluent in many languages"
apikey:
apiurl:
loras: []
tools: [tree, ls, find, symbol, readfile, putfile]
agents: [manager]
