#!/bin/env sh --tool

[ ! -d "$dir" ] && { echo "Error: directory not found"; exit 1; }

find "$dir" -ipath "*$pattern*" -type f ! -path "*/.*/*" ! -path "*/node_modules/*" 2>/dev/null | sort -u

exit

---

name: find
description: "Use only to search for files by pattern in the code base"
parameters:
  type: object
  properties:
    dir:
      type: string
      description: "Base directory to search. Always starts with ./"
      default: "."
    pattern:
      type: string
      description: "Optional globbing pattern. Use when you want to find files that match a certain pattern or extension."
      default: "*"
  required: []
