#!/usr/bin/env sh
set -e

error() {
  echo $@ >&2

  exit 1
}

if  [ "$1" = "version" ]; then
  exec cat /etc/VERSION
fi

CMD="/usr/local/bin/gelli-${1:-help}"

shift || true

[ -f "$CMD" ] && exec "$CMD" "$@" || error UNKNOWN COMMAND: $1 >&2
