#!/usr/bin/env sh
set -e

parse_hf() {
  spec=${1#hf:}
  repo=$(printf '%s\n' "$spec" | cut -d: -f1)
  file=$(printf '%s\n' "$spec" | cut -s -d: -f2)
  file="${file:-adapter_model.safetensors}"  # default LoRA filename
  out=$(echo "${repo}-${file}" | sed 's#[:/\]#-#g')
  dest="/loras/$out"

  [ -f "$dest" ] && { echo "${out%.*}"; return; }

  echo "↓ hf:$repo:$file → ${out%.*}" >&2

  url="https://huggingface.co/$repo/resolve/main/$file"

  echo "$dest" "$url"
}

parse() {
  case "$1" in
    hf:*) parse_hf "$1" ;;
    *) echo "/loras/$(basename "$1").safetensors" ;;
  esac
}

fetch() {
  dest="$1"
  url="$2"

  [ -f "$dest" ] || wget -qO "$dest" "$url" || error FAILED FETCH $url
  [ -f "$dest" ] && basename "${dest%.*}"
}

download() {
  for arg in "$@"; do
    fetch $(parse "$arg") || error MISSING $arg
  done
}

list() {
  glob="${1:-*}"

  cd /loras

  for f in $glob; do
    [ -f "$f" ] && printf '%s\n' "${f%.*}"
  done
}

delete() {
  for arg in "$@"; do
    file=$(parse "$arg")

    rm "$file"
  done
}

error() {
  echo $@ >&2

  exit 1
}

case "$1" in
  list) list "${@:2}";;
  delete) delete "${@:2}";;
  *) download "$@";;
esac
