#!/bin/env sh --tool

[ ! -d "$dir" ] && { echo "Error: directory not found"; exit 1; }

ls "$dir" | exec grep -v "\..*\|node_modules"

---

name: ls
description: List directory
parameters:
	type: object
	properties:
		dir:
			type: string
			description: Base directory
			default: "."
	required: []
