#!/bin/env sh --tool

[ ! -d "$dir" ] && { echo "Error: directory not found"; exit 1; }

ls "$dir" | exec grep -v "\..*\|node_modules"

---

name: ls
description: "Lists a directory one layer deep. Use  to show  the files in a specific directory to understand what is there."
parameters:
  type: object
  properties:
    dir:
      type: string
      description: "Directory to list. You should avoid absolute paths since your access is sandboxed."
  required: [dir]
