#!/gelli/bin//env sh '{"name":"ls","description":"List directory","parameters":{"type":"object","properties":{"dir":{"type":"string","description":"Base directory","default":"."}},"required":[]}}'

[ ! -d "$dir" ] && { echo "Error: directory not found"; exit 1; }

ls "$dir" | grep -v "\..*\|node_modules"
