#!/usr/bin/env sh
set -eu

# DEF: {"name":"read","description":"Read file contents","parameters":{"type":"object","properties":{"filename":{"type":"string","description":"File path to read"}},"required":["filename"]}}

filename=$(echo "${1:-"{}"}" | jq -r '.filename // empty')

[ -z "$filename" ] && { echo "Error: empty filename"; exit 1; }
[ ! -e "$filename" ] && { echo "Error: file not found"; exit 1; }

#todo check for size

cat "$filename"
