#!/usr/bin/env sh
set -eu

# DEF: {"name":"search","description":"Search codebase or directory for words or phrases","parameters":{"type":"object","properties":{"pattern":{"type":"string","description":"Search pattern"},"dir":{"type":"string","description":"Directory to search","default":"."}},"required":["pattern"]}}

pat="$(echo "${1:-"{}"}" | jq -r '.pattern // empty')"
dir="$(echo "${1:-"{}"}" | jq -r '.dir // "."')"

[ ! -d "$dir" ] && { echo "Error: directory not found"; exit 1; }
[ -z "$pat" ] && { echo "Error: empty pattern"; exit 1; }

grep -rE--exclude-dir='.git' --exclude-dir='node_modules'  -n "\\b$pat\\b" "$dir"  
