#!/usr/bin/env sh
set -eu

# DEF: {"name":"symbol","description":"Search entire codebase for symbol","parameters":{"type":"object","properties":{"search":{"type":"string","description":"symbol to search"},"dir":{"type":"string","description":"Base  directory","default":"."}},"required":["search"]}}

canonpath() {
  local dir=$(echo "$PWD/./${1#$PWD}" | awk -F/ '
    {
      n = split($0, a, "/")
      out = ""
      for(i=1;i<=n;i++){
        if(a[i]=="."||a[i]=="") continue
        else if(a[i]=="..") sub("/[^/]+$", "", out)
        else out=out"/"a[i]
      }
      print out ? out : "/"
    }
  ')
  echo ".${dir#$PWD}"
}

pat="$(echo "${1:-"{}"}" | jq -r '.search // empty')"

dir="$(echo "${1:-"{}"}" | jq -r '.dir // "."')"
dir=$(canonpath "$dir")

case "$dir" in
  .|./*) ;; *) echo "Error: outside work dir"; exit 1; ;;
esac

[ ! -d "$dir" ] && { echo "Error: directory not found"; exit 1; }
[ -z "$pat" ] && { echo "Error: empty search"; exit 1; }

find "$dir" -type f ! -path "*/.git/*" ! -path "*/node_modules/*" -exec grep -nE "\b$pat\b" {} + || echo "\"$pat\" not found in \""
